const products = [
  {
    _id: '1',
    name: 'Nintendo Switch',
    image: '/images/NS.jpeg',
    description:
      'The greatest Nintendo system since the Nintendo 64 with an insane amount of backwards compatability with their oneline NES and SNES emulators as well as releasing several Amazing nintendo games from the past, as well as having some of the greateswt games seen in recent history such as The Legend of Zelda: Breath of the Wild, Xenoblade Chronicles 2, Super Mario Odyssey, and Dragon Quest 11: Echos of an Elusive Age',
    brand: 'Nintendo',
    category: 'Consoles',
    price: 399.99,
    countInStock: 10,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Nintendo 64',
    image: '/images/N64.jpg',
    description:
      'One of the greatest gaming consoles of all time, defined what 3d gaming needed to be, so few companies made perfection on their first enterance into 3d but Nintendo knocked it out of the park with the N64, including hit games such as Super Mario 64, 007: Golden Eye, Mario Kart 64, Star Fox 64, Super Smash Bros, and the almight, greatest game of all time, the perfection of gaming in any and all its forms... The Legend of Zelda: Ocorina of Time',
    brand: 'Nintendo',
    category: 'Consoles',
    price: 99.99,
    countInStock: 7,
    rating: 5,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Nintendo Gamecube',
    image: '/images/GC.jpg',
    description:
      'The Nintendo GameCube[b][c] is a home video game console released by Nintendo in Japan and North America in 2001 and in PAL territories in 2002. The GameCube is Nintendos entry in the sixth generation of video game consoles and is the successor to their previous console, the Nintendo 64.',
    brand: 'Nintendo',
    category: 'Consoles',
    price: 149.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Super Nintendo Entertainment System',
    image: '/images/SNES.jpeg',
    description:
      'The System that brought the golden age of RPGs with games like Chrono trigger, Final Fantasy 6, and Earthbound',
    brand: 'Nintendo',
    category: 'Consoles',
    price: 49.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Nintendo Entertainment System',
    image: '/images/NES.jpg',
    description:
      'the console that put Nintendo on the map, with such crowning achievments as The Legend of Zelda, Super Mario Bros, Contra, Castlevania, and MegaMan',
    brand: 'Nintendo',
    category: 'Consoles',
    price: 49.99,
    countInStock: 7,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Nintendo Game Boy',
    image: '/images/GB.jpg',
    description:
      'This is the reason hand held gaming became a thing, the start of portable gaming with good, swap-able games. inclusind such hits as, Pokemon Red and Blue, The Legend of Zelda: Links Awakening, Super Mario Land 2, and Tetris ',
    brand: 'Nintendo',
    category: 'Hand Held Consoles',
    price: 29.99,
    countInStock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Nintendo Game Boym Color',
    image: '/images/GBC.jpg',
    description:
      'the natural evolution of the original GameBoy, get the same portabilty in your gameboy but now with COLOR, including such hit games as Pokemon: gold and Silver, The Legend of Zelda:Oracle of Ages and Oracle of Seasons, Super MArio Bros Delux, and Crystalis  ',
    brand: 'Nintendo',
    category: 'Hand Held Consoles',
    price: 29.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 19,
  },
  {
    _id: '8',
    name: 'Nintendo Virtual Boy',
    image: '/images/VB.jpg',
    description:
      'the one failure in nintendos history, released before it was ready, still fun, but not up to the usual quality that we have come to expect from nintendo, only 14 games were released for this system. ',
    brand: 'Nintendo',
    category: 'Hand Held Consoles',
    price: 19.99,
    countInStock: 0,
    rating: 2.5,
    numReviews: 8,
  },
]

export default products